import type { Meta, StoryObj } from '@storybook/react-vite';
import { GlowApp, GlowComparison } from './glow';
const meta = { title: 'Alternate Design/Glow', component: GlowApp, parameters: { layout: 'centered' }, argTypes: { theme: { control: 'inline-radio', options: ['dark', 'light'] }, initialScreen: { control: 'select', options: ['feed', 'discover', 'play', 'profile', 'messages', 'badges', 'clinics', 'live'] } } } satisfies Meta<typeof GlowApp>;
export default meta;
type Story = StoryObj<typeof meta>;
export const StartFeed: Story = { args: { theme: 'dark', initialScreen: 'feed' } };
export const StartFeedLight: Story = { args: { theme: 'light', initialScreen: 'feed' } };
export const Discover: Story = { args: { initialScreen: 'discover' } };
export const Play: Story = { args: { initialScreen: 'play' } };
export const Profile: Story = { args: { initialScreen: 'profile' } };
export const Messages: Story = { args: { initialScreen: 'messages' } };
export const CompareThemes: Story = { render: () => <GlowComparison />, parameters: { layout: 'fullscreen' } };
