import { useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowUpRight, Bell, BatteryFull, CalendarDays, Check, ChevronDown, ChevronRight, MapPin, MessageCircle, Navigation, Search, Signal, Sparkles, Trophy, Wifi, Zap } from 'lucide-react';
import { Action, IconButton, PageHeading, Progress, Tile } from '../../components/alternate/primitives';

const logo = new URL('../../assets/brand/logotype.png', import.meta.url).href;
const asset = (name: string) => new URL(`./assets/${name}.png`, import.meta.url).href;
const assets = { court: asset('court'), feed: asset('feed'), hero: asset('atp-hero'), atp: asset('atp-tile'), niklas: asset('niklas'), me: asset('nav-me'), coaches: asset('coaches') };
export type Screen = 'feed' | 'discover' | 'play' | 'messages' | 'profile' | 'badges' | 'clinics' | 'live';
export type Theme = 'dark' | 'light';
const labels: Record<Screen, string> = { feed: 'Start feed', discover: 'Discover', play: 'Play', messages: 'Messages', profile: 'Profile', badges: 'Achievements', clinics: 'Clinics', live: 'ATP Live' };

function LivePanel({ hero = false, onClick }: { hero?: boolean; onClick: () => void }) {
  return <Tile className={`glow-live ${hero ? 'hero' : ''}`} onClick={onClick} aria-label="Open ATP Tour Live"><img src={hero ? assets.hero : assets.atp} alt="ATP Tour Live" /></Tile>;
}
function Feed({ go }: { go: (screen: Screen) => void }) {
  const [expanded, setExpanded] = useState(false);
  return <><LivePanel hero onClick={() => go('live')} />
    <div className="glow-grid">
      <Tile className="glow-feed-tile" onClick={() => go('badges')}><span className="glow-eyebrow">Badges</span><h2>Unlock<br />Achievements</h2><Progress value={17} label="Achievements unlocked" /></Tile>
      <LivePanel onClick={() => go('live')} />
      <Tile className="glow-feed-tile" onClick={() => go('clinics')}><span className="glow-eyebrow">Clinics</span><h2>Livechat with<br />pro coaches</h2><span className="glow-coaches"><img src={assets.coaches} alt="Three coaches" />+ 12 online now</span></Tile>
      <Tile className="glow-feed-tile glow-nearby" onClick={() => go('discover')}><img src={assets.court} alt="Players at a pickleball court" /><span><span className="glow-distance"><Navigation size={11} fill="currentColor" />5.3 km away from you</span><strong>Freddes Pickleballsällskap i Sundyberg &amp; Bromma</strong></span></Tile>
    </div>
    <article className="glow-post"><img className="glow-post-cover" src={assets.feed} alt="Friends playing pickleball" /><div className="glow-post-body"><img className="glow-avatar" src={assets.niklas} alt="" /><div className="glow-post-copy"><strong>Niklas Sidfalk</strong><p>{expanded ? 'Det var väldigt kul att spela idag! Ska vi kanske försöka att göra om detta nästa vecka?' : 'Det var väldigt kul att spela idag! Ska vi kanske försöka att göra om detta näst...'}</p></div><IconButton label={expanded ? 'Collapse post' : 'Read full post'} aria-expanded={expanded} onClick={() => setExpanded(!expanded)}><ChevronDown size={18} style={{ transform: expanded ? 'rotate(180deg)' : undefined }} /></IconButton></div></article>
  </>;
}
const venues = [
  { name: 'Freddes Pickleballsällskap', area: 'Sundbyberg & Bromma', distance: '5.3 km', sport: 'Pickleball', detail: 'Outdoor · 4 courts' },
  { name: 'Bromma Tennis', area: 'Bromma', distance: '6.1 km', sport: 'Tennis', detail: 'Indoor · 6 courts' },
  { name: 'Sundbyberg Padel', area: 'Sundbyberg', distance: '3.8 km', sport: 'Padel', detail: 'Indoor · 8 courts' },
];
function Discover({ go }: { go: (screen: Screen) => void }) {
  const [query, setQuery] = useState(''); const [sport, setSport] = useState('All');
  const matches = venues.filter(v => (sport === 'All' || v.sport === sport) && `${v.name} ${v.area}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeading eyebrow="YOUR NEXT GOOD GAME" title="Find your court.">Good people. Great places to play.</PageHeading><input className="glow-search" aria-label="Search clubs or places" placeholder="Search clubs or places" value={query} onChange={e => setQuery(e.target.value)} /><div className="glow-filters">{['All', 'Pickleball', 'Tennis', 'Padel'].map(s => <button key={s} aria-pressed={s === sport} onClick={() => setSport(s)}>{s}</button>)}</div><div className="glow-row"><strong>Near you</strong><span className="glow-muted">{matches.length} {matches.length === 1 ? 'place' : 'places'}</span></div><div className="glow-stack" style={{ marginTop: 12 }}>{matches.map(v => <Tile key={v.name} onClick={() => go('play')} className="glow-match">{v.sport === 'Pickleball' && <img src={assets.court} alt="Pickleball players" style={{ width: '100%', height: 135, objectFit: 'cover', borderRadius: 8 }} />}<span className="glow-row"><span className="glow-pill">{v.sport}</span><span className="glow-distance"><MapPin size={13} />{v.distance}</span></span><h2>{v.name}</h2><span className="glow-muted">{v.area} · {v.detail}</span><span className="glow-row"><strong>Find a game</strong><ArrowUpRight size={19} /></span></Tile>)}{matches.length === 0 && <div className="glow-notice">No clubs found. Try another place or sport.</div>}</div></>;
}
function Play() {
  const [sport, setSport] = useState('Pickleball'); const [joined, setJoined] = useState<string[]>([]);
  return <><PageHeading eyebrow="LESS PLANNING. MORE PLAYING." title="Your next game.">Find your people on the court.</PageHeading><div className="glow-filters">{['Pickleball', 'Tennis', 'Padel'].map(s => <button key={s} aria-pressed={sport === s} onClick={() => setSport(s)}>{s}</button>)}</div><div className="glow-stack">{['After-work doubles', 'Sunday social'].map((title, i) => { const id = `${sport}-${title}`; const isJoined = joined.includes(id); return <section className="glow-tile glow-match" key={id}><span className="glow-row"><span className="glow-pill">{isJoined ? 'You’re in' : 'Open game'}</span><span className="glow-muted">{sport}</span></span><h2>{title}</h2><span className="glow-row"><CalendarDays size={18} /><span>{i === 0 ? 'Today · 18:00–19:30' : 'Sunday · 10:00–11:30'}</span></span><span className="glow-row"><MapPin size={18} /><span>{sport === 'Pickleball' ? 'Freddes, Sundbyberg' : sport === 'Tennis' ? 'Bromma Tennis' : 'Sundbyberg Padel'}</span></span><span className="glow-row"><img src={assets.coaches} width={80} alt="Players attending" /><span className="glow-muted">{isJoined ? '4 of 4 players · Full' : '3 of 4 players · 1 spot left'}</span></span><Action secondary={isJoined} onClick={() => setJoined(isJoined ? joined.filter(x => x !== id) : [...joined, id])}>{isJoined ? 'Leave game' : 'Join game'}</Action></section>; })}</div><p className="glow-muted" style={{ fontSize: 11, marginTop: 15 }}>Demo games — joining updates this preview only.</p></>;
}
function Profile({ go }: { go: (screen: Screen) => void }) {
  return <><div className="glow-profile"><img className="glow-avatar" src={assets.me} alt="Your profile" /><h1>Hey, Oliver.</h1><span className="glow-muted">A good day starts on court.</span></div><div className="glow-tile glow-stats"><div><strong>24</strong><span>Games played</span></div><div><strong>8</strong><span>Friends</span></div><div><strong>1,259</strong><span>Points</span></div></div><h2 className="glow-section-title">Keep your momentum</h2><Tile className="glow-match" onClick={() => go('badges')}><span className="glow-row"><Trophy color="var(--glow-green)" /><strong>Your achievements</strong><ChevronRight size={18} /></span><h2>Small wins. Big energy.</h2><p className="glow-muted">You’ve unlocked 2 of 12 badges.</p><Progress value={17} label="Achievements unlocked" /></Tile><h2 className="glow-section-title">Your court life</h2><div className="glow-stack">{([['play', 'Upcoming games'], ['discover', 'Explore clubs'], ['messages', 'Your conversations']] as const).map(([screen, title]) => <Tile key={screen} onClick={() => go(screen)}><span className="glow-row"><strong>{title}</strong><ChevronRight size={18} /></span></Tile>)}</div></>;
}
function Messages() {
  const [open, setOpen] = useState(false); const [draft, setDraft] = useState(''); const [sent, setSent] = useState<string[]>([]);
  return <><PageHeading eyebrow="GOOD GAMES START HERE" title={open ? 'Niklas Sidfalk' : 'Your people.'} />{open ? <><Action secondary onClick={() => setOpen(false)}>Back to conversations</Action><div className="glow-stack" style={{ marginTop: 20 }}><div className="glow-tile">Same time next week? 🎾</div>{sent.map((s, i) => <div className="glow-tile" key={i} style={{ marginLeft: 30 }}>{s}</div>)}</div><form style={{ marginTop: 20 }} onSubmit={e => { e.preventDefault(); if (draft.trim()) { setSent([...sent, draft.trim()]); setDraft(''); } }}><input aria-label="Your message" className="glow-search" placeholder="Write a message…" value={draft} onChange={e => setDraft(e.target.value)} /><Action disabled={!draft.trim()}>Send demo message</Action></form><p className="glow-muted">Messages stay in this preview.</p></> : <Tile onClick={() => setOpen(true)}><span className="glow-row"><img className="glow-avatar" src={assets.niklas} alt="" /><div><strong>Niklas Sidfalk</strong><p className="glow-muted">Same time next week? 🎾</p></div><ChevronRight size={18} /></span></Tile>}</>;
}
function Detail({ screen }: { screen: Screen }) {
  const [selected, setSelected] = useState(false);
  if (screen === 'badges') return <><PageHeading eyebrow="EVERY GAME COUNTS" title="Look how far you’ve come.">2 badges unlocked. Plenty more to play for.</PageHeading><section className="glow-tile glow-match"><Trophy color="var(--glow-green)" size={36} /><h2>Your next milestone</h2><p className="glow-muted">Play with someone new to grow your court circle.</p><Progress value={17} label="Achievements unlocked" /></section><div className="glow-grid">{['First serve', 'Team player', 'Court regular', 'Game changer'].map((title, i) => <section key={title} className="glow-tile glow-match"><Trophy size={32} color={i < 2 ? 'var(--glow-green)' : 'var(--glow-muted)'} /><h2>{title}</h2><span className="glow-muted">{i < 2 ? 'Unlocked' : 'Keep playing to unlock'}</span></section>)}</div></>;
  if (screen === 'clinics') return <><PageHeading eyebrow="A LITTLE GUIDANCE. A BETTER GAME." title="Meet your next coach.">Make progress with people who love the game.</PageHeading><section className="glow-tile glow-match"><img src={assets.court} alt="Coach with a player" style={{ width: '100%', borderRadius: 8 }} /><span className="glow-pill">12 coaches online</span><h2>Bring your questions.</h2><p className="glow-muted">Technique, tactics or your first game. Join the conversation.</p><Action onClick={() => setSelected(!selected)}>{selected ? 'Leave demo waiting room' : 'Join live clinic'}</Action>{selected && <p role="status">You’re in the demo waiting room. No live session is connected.</p>}</section></>;
  return <><PageHeading eyebrow="ATP TOUR" title="Courtside, wherever you are.">Your home for the live game.</PageHeading><LivePanel hero onClick={() => setSelected(!selected)} /><h2 className="glow-section-title">Live coverage</h2><section className="glow-tile glow-match"><h2>The next point starts here.</h2><p className="glow-muted">This is a preview of the broadcast destination. Live scores and video will come from the app’s sports provider.</p><Action onClick={() => setSelected(!selected)}>{selected ? 'Reminder saved' : 'Try a match reminder'}</Action>{selected && <span role="status" className="glow-row"><Check size={18} />Reminder enabled for this demo.</span>}</section></>;
}
export function GlowApp({ theme = 'dark', initialScreen = 'feed' }: { theme?: Theme; initialScreen?: Screen }) {
  const [screen, setScreen] = useState<Screen>(initialScreen); const [notifications, setNotifications] = useState(false);
  const go = (next: Screen) => { setScreen(next); setNotifications(false); };
  let content: ReactNode;
  switch (screen) { case 'feed': content = <Feed go={go} />; break; case 'discover': content = <Discover go={go} />; break; case 'play': content = <Play />; break; case 'profile': content = <Profile go={go} />; break; case 'messages': content = <Messages />; break; default: content = <Detail key={screen} screen={screen} />; }
  return <div className="raqt-glow glow-phone" data-theme={theme}><div className="glow-status" aria-hidden="true"><span>9:41</span><span><Signal size={19} fill="currentColor" /><Wifi size={17} /><BatteryFull size={25} /></span></div><header className="glow-header">{screen === 'feed' ? <img className="glow-logo" src={logo} alt="RAQT" /> : <IconButton label="Back to start feed" onClick={() => go('feed')}><ArrowLeft size={23} /></IconButton>}<div className="glow-header-actions"><button className="glow-points" onClick={() => go('badges')}><Sparkles size={19} />1259 points</button><IconButton label="Notifications" aria-expanded={notifications} onClick={() => setNotifications(!notifications)}><Bell size={21} fill="currentColor" /><span className="glow-dot" /></IconButton></div></header><main className="glow-content" key={screen} aria-label={labels[screen]}>{notifications && <div className="glow-notice" role="status"><strong>You’re all caught up.</strong><p>Your game updates will appear here.</p></div>}{content}</main><nav className="glow-nav" aria-label="Main navigation"><IconButton label="Discover courts" aria-current={screen === 'discover' ? 'page' : undefined} onClick={() => go('discover')}><Search /></IconButton><IconButton label="Nearby clubs" onClick={() => go('discover')}><MapPin /></IconButton><button className="glow-play" aria-label="Find a game to play" aria-current={screen === 'play' ? 'page' : undefined} onClick={() => go('play')}><Zap size={22} /><span>PLAY</span></button><IconButton label="Messages" aria-current={screen === 'messages' ? 'page' : undefined} onClick={() => go('messages')}><MessageCircle /></IconButton><IconButton label="Your profile" aria-current={screen === 'profile' ? 'page' : undefined} onClick={() => go('profile')}><img className="glow-avatar" src={assets.me} alt="" /></IconButton><span className="glow-home-indicator" aria-hidden="true" /></nav></div>;
}
export function GlowComparison() {
  const [screen, setScreen] = useState<Screen>('feed');
  return <div className="glow-preview"><div className="glow-preview-toolbar"><h1>RAQT / Glow exploration</h1>{(['feed', 'discover', 'play', 'profile', 'messages'] as Screen[]).map(s => <button key={s} aria-pressed={screen === s} onClick={() => setScreen(s)}>{labels[s]}</button>)}</div><div className="glow-preview-phones">{(['dark', 'light'] as Theme[]).map(theme => <div key={theme}><p className="glow-preview-label">{theme === 'dark' ? '01 / AFTER DARK' : '02 / DAYLIGHT'}</p><GlowApp key={`${theme}-${screen}`} theme={theme} initialScreen={screen} /></div>)}</div></div>;
}
